<?php

/**
 * @file
 * Module's main file.
 */

use Drupal\mvs\Constant;
use Drupal\mvs\enum\NodeBundle;
use Drupal\tmdb\enum\TmdbImageFormat;
use Drupal\tmdb\TmdbApiAdapter;

/**
 * Implements hook_theme().
 */
function mvs_theme($existing, $type, $theme, $path): array {
  return [
    'movies_language_switcher' => [
      'variables' => [
        'active_label' => NULL,
        'links' => [],
      ],
    ],
    'mvs_error_page' => [
      'variables' => [
        'error_code' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function mvs_page_attachments(array &$attachments): void {
  if (Drupal::routeMatch()->getRouteName() == 'entity.node.canonical') {
    /** @var \Drupal\node\Entity\Node $node */
    $node = Drupal::routeMatch()->getParameter('node');

    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'meta',
        '#attributes' => [
          'property' => 'og:title',
          'content' => $node->getTitle(),
        ],
      ],
      'og-title',
    ];
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'meta',
        '#attributes' => [
          'property' => 'og:type',
          'content' => $node->bundle() == NodeBundle::movie() ? 'video.movie' : 'video.tv_show',
        ],
      ],
      'og-type',
    ];
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'meta',
        '#attributes' => [
          'property' => 'og:image',
          'content' => Constant::TMDB_IMAGE_BASE_URL . TmdbImageFormat::w185()
              ->key() . $node->{'field_poster'}->value,
        ],
      ],
      'og-image',
    ];
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'meta',
        '#attributes' => [
          'property' => 'og:url',
          'content' => $node->toUrl('canonical', ['absolute' => TRUE])
            ->toString(),
        ],
      ],
      'og-url',
    ];
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'meta',
        '#attributes' => [
          'property' => 'og:description',
          'content' => (new TmdbApiAdapter())->getCommonFieldValue($node, 'overview') ?? '',
        ],
      ],
      'og-description',
    ];

    $language_manager = \Drupal::languageManager();
    $current = $language_manager->getCurrentLanguage()->getId();
    $languages = $language_manager->getLanguages();

    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'meta',
        '#attributes' => [
          'property' => 'og:locale',
          'content' => _get_locale_code_ISO8859_1($current),
        ],
      ],
      'og-locale',
    ];

    foreach ($languages as $language) {
      $language = $language->getId();

      if ($language != $current) {
        $attachments['#attached']['html_head'][] = [
          [
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => [
              'property' => 'og:locale:alternate',
              'content' => _get_locale_code_ISO8859_1($language),
            ],
          ],
          "og-locale-alternate-$language",
        ];
      }
    }
  }
}

/**
 * Implements hook_element_info_alter().
 *
 * @deprecated
 *   Remove after views will be removed.
 */
function mvs_element_info_alter(array &$info) {
  $info['view']['#pre_render'][] = [
    Drupal\mvs\Element\View::class,
    'preRenderViewElement',
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * @deprecated
 *   Remove after views will be removed.
 */
function mvs_form_views_exposed_form_alter(&$form) {
  $bundle = NULL;
  $remove_animation_filter = TRUE;

  switch ($form['#id']) {
    case 'views-exposed-form-movies-home':
      $bundle = ['movie', 'tv'];
      $remove_animation_filter = FALSE;
      break;

    case 'views-exposed-form-movies-movie':
      $bundle = 'movie';
      break;

    case 'views-exposed-form-movies-tv':
      $bundle = 'tv';
      break;

    case 'views-exposed-form-movies-animation':
      $bundle = ['movie', 'tv'];
      break;

  }

  if ($bundle) {
    // Get genres for current bundle.
    $genres_by_bundle = Drupal::service('entity_finder')
      ->findTermsGenres()
      ->addCondition('field_used_in', $bundle)
      ->execute();

    // Get genres (options) from form.
    $genres = &$form['field_genres_target_id']['#options'];
    // Filter only genres used in current bundle.
    $genres = array_intersect_key($genres, $genres_by_bundle);
    // Sort by name ASC.
    asort($genres);

    // Remove "Animation" filter from some view.
    if ($remove_animation_filter && $tid = _get_animation_term_id()) {
      unset($genres[$tid]);
    }
  }
}

/**
 * Helper function returns ID of term "Animation".
 *
 * @return int|null
 */
function _get_animation_term_id(): ?int {
  return Drupal::service('entity_finder')
    ->findTermsGenres()
    ->addCondition('name', 'Animation')
    ->reduce()
    ->execute();
}

/**
 * Helper function converts locale code from ISO 639-1 to ISO 8859-1.
 *
 * @param string $langcode
 *   Langcode in ISO 639-1 format e.g. "en", "uk".
 *
 * @return string
 *   Langcode in ISO 8859-1 format e.g. "en_US", "uk_UA".
 */
function _get_locale_code_ISO8859_1(string $langcode): string {
  return match ($langcode) {
    'en' => 'en_US',
    'uk' => 'uk_UA',
  };
}
