<?php

/**
 * @file
 * Module's main file.
 */

/**
 * Implements hook_theme().
 */
function mvs_theme($existing, $type, $theme, $path): array {
  return [
    'movies_language_switcher' => [
      'variables' => [
        'active_label' => NULL,
        'links' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_element_info_alter().
 *
 * @deprecated
 *   Remove after views will be removed.
 */
function mvs_element_info_alter(array &$info) {
  $info['view']['#pre_render'][] = [
    Drupal\mvs\Element\View::class,
    'preRenderViewElement',
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * @deprecated
 *   Remove after views will be removed.
 */
function mvs_form_views_exposed_form_alter(&$form) {
  $bundle = NULL;
  $remove_animation_filter = TRUE;

  switch ($form['#id']) {
    case 'views-exposed-form-movies-home':
      $bundle = ['movie', 'tv'];
      $remove_animation_filter = FALSE;
      break;

    case 'views-exposed-form-movies-movie':
      $bundle = 'movie';
      break;

    case 'views-exposed-form-movies-tv':
      $bundle = 'tv';
      break;

    case 'views-exposed-form-movies-animation':
      $bundle = ['movie', 'tv'];
      break;

  }

  if ($bundle) {
    // Get genres for current bundle.
    $genres_by_bundle = Drupal::service('entity_finder')
      ->findTermsGenres()
      ->addCondition('field_used_in', $bundle)
      ->execute();

    // Get genres (options) from form.
    $genres = &$form['field_genres_target_id']['#options'];
    // Filter only genres used in current bundle.
    $genres = array_intersect_key($genres, $genres_by_bundle);
    // Sort by name ASC.
    asort($genres);

    // Remove "Animation" filter from some view.
    if ($remove_animation_filter && $tid = _get_animation_term_id()) {
      unset($genres[$tid]);
    }
  }
}

/**
 * Helper function returns ID of term "Animation".
 *
 * @return int|null
 */
function _get_animation_term_id(): ?int {
  return Drupal::service('entity_finder')
    ->findTermsGenres()
    ->addCondition('name', 'Animation')
    ->reduce()
    ->execute();
}
