<?php

/**
 * @file
 * TMDb main file for hooks.
 */

/**
 * Implements hook_theme().
 */
function tmdb_theme($existing, $type, $theme, $path) {
  return [
    'tmdb_field' => [
      'variables' => [
        'content' => NULL,
        'css_class' => NULL,
      ],
    ],
    'collection' => [
      'variables' => [
        'title' => NULL,
        'poster' => NULL,
        'items' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function tmdb_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  $p = \Drupal::service('entity_creator')::NODE_TITLE_EMPTY_PLACEHOLDER;
  /** @var \Drupal\node\Entity\Node $entity */
  if ($entity->getTitle() === $p) {
    // Update placeholder fields if need.
    \Drupal::service('tmdb.adapter')->updateMovieOrTvPlaceholderFields($entity);
    // Update title and poster on page.
    $build['title'] = $entity->{'title'}->view($view_mode);
    $build['field_poster'] = $entity->{'field_poster'}->view($view_mode);
  }
}
