<?php

/**
 * @file
 * TMDb main file for hooks.
 */

/**
 * Implements hook_theme().
 */
function tmdb_theme($existing, $type, $theme, $path) {
  return [
    'tmdb_field' => [
      'variables' => [
        'content' => NULL,
        'css_class' => NULL,
      ],
    ],
    'field_with_label' => [
      'variables' => [
        'label' => NULL,
        'content' => NULL,
      ],
    ],
    'collection' => [
      'variables' => [
        'title' => NULL,
        'poster' => NULL,
        'items' => NULL,
      ],
    ],
    'tmdb_attachable_teasers_wrapper' => [
      'variables' => [
        'tmdb_attachable_teasers' => NULL,
      ],
    ],
    'tmdb_attachable_teasers' => [
      'variables' => [
        'type' => NULL,
        'items' => NULL,
        'page' => NULL,
        'more_button' => NULL,
      ],
    ],
    'tmdb_teaser' => [
      'variables' => [
        'bundle' => NULL,
        'tmdb_id' => NULL,
        'poster' => NULL,
        'imdb_rating' => NULL,
        'title' => NULL,
        'original_title' => NULL,
      ],
    ],
    'person' => [
      'variables' => [
        'avatar' => NULL,
        'name' => NULL,
        'role' => NULL,
        'department' => NULL,
        'job' => NULL,
      ],
    ],
    'video' => [
      'variables' => [
        'name' => NULL,
        'size' => NULL,
        'key' => NULL,
        'language' => NULL,
      ],
    ],
  ];
}
